### ISSUE TITLE
circleci sonarQube scan currently fails for forked PR builds

### ISSUE THREAD

**Issue by johanneseschrig** [corona-warn-app/cwa-server#237]
## Describe the bug

PRs from forks will fail with `[ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.7.0.1746:sonar (default-cli) on project server: Parameter 'sonar.pullrequest.branch' is mandatory for a pull request analysis`. 

Needs to be fixed.

**Comment by johanneseschrig** [comment]
Consider: https://github.com/corona-warn-app/cwa-server/pull/236#issuecomment-632226214

**Comment by jonaskoepper** [comment]
Seems this is resolved? My PR, based on a fork, meanwhile builds: https://github.com/corona-warn-app/cwa-server/pull/239

**Comment by johanneseschrig** [comment]
Hi Jonas! Unfortunately we currently just work around it with https://github.com/corona-warn-app/cwa-server/pull/236. This way we don't block any PRs, but sonar still doesn't run on community PRs atm.

**Comment by CCFenner** [comment]
Recent comment from Sonar officials in https://community.sonarsource.com/t/how-to-use-sonarcloud-with-a-forked-repository-on-github/7363/8


> > Are there any news? The Issue https://jira.sonarsource.com/browse/MMF-1371 is not so active :slight_smile:

> Not yet! I recommend to check again after 4-6 months.

//fyi @jhagestedt

**Comment by CCFenner** [comment]
A workaround for this could be a chat-ops-like workflow. The following would be needed:

- a workflow that listens to *issue comments*
  - if specific comment (e.g. `/sonar`) is posted on a fork pr push the changes from the fork to a dedicated branch on the upstream repository
- a workflow that runs sonar *on push* to the dedicated branch

This would require a PAT of a personal or technical user in repository secrets with repo write permissions as the default `secrets.GITHUB_TOKEN` is not sufficient.

Would this be a way to go?
